check50:  
  files: &check50_files # "Alias", in YAML-speak, for the files we include in check50
    - !exclude "*"
    - !require main.py
  checks:
    Say hello to John:
      - run: python3 main.py
        stdin: John
        stdout: Hello, John
        exit: 0

submit50:
  files: *check50_files
